### ISSUE TITLE
Buttons in admin interface should match selected admin color scheme

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-fields#73]
<img width="1892" alt="screen shot 2017-07-05 at 1 50 30 pm" src="https://user-images.githubusercontent.com/4993131/27880051-a1ec51bc-6191-11e7-99b3-4247a6815420.png">
The buttons on the right hand side of the settings should be the same as the selected WP admin color scheme's primary color.

**Comment by d4mation** [comment]
I'm not sure they should match the Primary color. That seems to go against what that button is for.

The Primary color is used for things like "Save" changes in the WP Backend. Things which are "positive" interactions.

Those buttons on the side are "Delete" buttons. "Negative" interactions.

I think using the Primary color would be confusing to the User if it were the same color as the "Save" button. Not very good UX.

Looking at your screenshot, I think you're using the "Midnight" theme? It is hard to say for certain because the palettes shown on the Profile Edit screen don't seem to consistently match up with the Theme itself. For example, the "Blue" theme has Orange Primary and Badge colors but nowhere in the palette is Orange shown.

Maybe the Delete button could take the Badge color then in order to match it to the Theme better?

With your chosen Theme I can see having Red as the Delete button could be confusing since the Save Changes button is also a Red color.

![image](https://user-images.githubusercontent.com/7770631/28177977-c4be34aa-67ca-11e7-841b-1c74692bc2e3.png)

**Comment by d4mation** [comment]
Also, whatever we do here should probably be applied to EDD Slack as well since their interfaces are based on each others.

**Comment by brashrebel** [comment]
I see your point and think we can find a compromise somewhere. I don't think we should introduce new colors or diverge from established principles throughout the admin. In most places where something can be removed it is not a button at all but rather a text hyperlink styled red.  In EDD's tax rates table a gray button is used so we could follow that as a model. In fact you could even consider making the field group title editable inline instead of in the modal similar to how values get set in the tax rates table. Just a thought.

**Comment by d4mation** [comment]
We could go the red text in a gray button route. I don't like the idea of two gray buttons (Edit and Delete) next to each other with just red text differentiating them visually though.

I went ahead and gave using the "Update" Badge Color as the delete button color per-Theme a try. I think it looks pretty good, honestly. (Screenshots are from EDD Slack since the UI is basically the same)

Default Theme:
![image](https://user-images.githubusercontent.com/7770631/28433325-2cadb494-6d59-11e7-9885-53c569817abe.png)

Light Theme (The Badge color is only slightly different than the Default Theme, so it is hard to tell):
![image](https://user-images.githubusercontent.com/7770631/28433313-20d380a4-6d59-11e7-84b8-bb3f8980e6f6.png)

Blue Theme: 
![image](https://user-images.githubusercontent.com/7770631/28433297-1366ca66-6d59-11e7-8495-ca4d47d99478.png)

Coffee Theme:
![image](https://user-images.githubusercontent.com/7770631/28433281-06ac16f0-6d59-11e7-8bad-45042bba7b03.png)

Ectoplasm Theme:
![image](https://user-images.githubusercontent.com/7770631/28433203-c06ead74-6d58-11e7-8902-f1d6ddf18096.png)

Midnight Theme:
![image](https://user-images.githubusercontent.com/7770631/28433222-d741d22e-6d58-11e7-93f9-7591067297b7.png)

Ocean Theme:
![image](https://user-images.githubusercontent.com/7770631/28433248-e93676b0-6d58-11e7-988f-e39cbdddf12e.png)

Sunrise Theme:
![image](https://user-images.githubusercontent.com/7770631/28433264-f8561952-6d58-11e7-9de1-0da90fe04b42.png)

**Comment by brashrebel** [comment]
I'm good with this.
