### ISSUE TITLE
Fields shortcode inserter broken

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/edd-fields#74]
Testing on latest `develop` and clicking to insert a field or a fields table into a download body does nothing and throws the following in the console:

`Uncaught Error: Could not find control by type: select`

**Comment by d4mation** [comment]
I cannot reproduce this on my end. 

The Select TinyMCE Field Type is a custom one I had to add because the included "Listbox" Field Type is super limiting. 

I'm including it in a special way due to WordPress not allowing you to enqueue those types of scripts in a "normal" way (WP doesn't either behind-the-scenes)

https://github.com/realbigplugins/edd-fields/blob/c5225c67fab1dc076e4261e5ff4513ebd84713d3/core/admin/class-edd-fields-post-edit.php#L34

https://github.com/realbigplugins/edd-fields/blob/c5225c67fab1dc076e4261e5ff4513ebd84713d3/core/admin/class-edd-fields-post-edit.php#L346-L357

![image](http://i.imgur.com/b4DjRg9.gif)

**Comment by brashrebel** [comment]
Definitely can't get it to work. Multiple browsers, separate installs, different PHP versions, no other plugins, everything. Cannot get that to do anything. Throws the JS error only every single time.

**Comment by d4mation** [comment]
So, turns out this is an issue with WP 4.8. I was still rocking WP 4.7 on that install for some reason.

I'll look into this.

**Comment by d4mation** [comment]
Looks like in WP 4.8 they updated TinyMCE so that it now has its own `<select>` element, rendering my code unnecessary. Bittersweet since it took a fair amount of research to get working (TinyMCE is a horrible mess), but I'm also glad it isn't needed anymore.

Going to take some refactoring to work with the new input element, but I think it should be otherwise.

**Comment by d4mation** [comment]
This should be fixed now, @brashrebel.

The new TinyMCE SelectBox Control Type wouldn't have done quite all we needed without some serious modification, so I just kept the one that I was using before and renamed it to make future collisions less likely (I had named it "Select" and TinyMCE chose "SelectBox").

This was the only line of code that we needed to add which wasn't required in WP 4.7 it appears:

`tinymce.ui.Factory.add( 'RBMSelect', tinymce.ui.RBMSelect );`

**Comment by d4mation** [comment]
While I haven't tested it in WP 4.7 directly, WP 4.7 uses TinyMCE 4.5.6 and the above function exists there as well.

**Comment by brashrebel** [comment]
Confirmed fixed.
